config/routes.rb
Sagebody::Application.routes.draw do
  get "users/new"

  match 'home/index' =>'home#index'
  match 'doctors/main' => 'doctors#main' # order is important!
  match 'doctors/:doctor' =>'doctors#doctor'
 resources :users
 

  root :to => "main#index"

end

app/models/users.rb
class Users < ActiveRecord::Base
    attr_accessible :email, :password, :password_confirmation, :first_name, :last_name

    attr_accessor :password
    before_save :encrypt_password

    validates_confirmation_of :password
    validates_presence_of :password, :on => :create
    validates_presence_of :email
    validates_uniqueness_of :email

    def self.authenticate(email, password)
      user = find_by_email(email)
      if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
        user
      else
        nil
      end
    end

    def encrypt_password
      if password.present?
        self.password_salt = BCrypt::Engine.generate_salt
        self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
      end
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  
  def doctor
    render :doctor
  end
  
  def main
    render :main
  end
  

  
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  
  def index
    render :index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Registered!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/doctors/doctor.html.erb
<!--
	<?php
		$pageTitle = "SageBody:Dr. ". $_REQUEST['dr']." Prescriptions";
		include_once('util.php');
		include_once("_html_head.php");
		$num=$_REQUEST['num'];
		include_once("dbinfo/db.php");
		$db=ConnectToDb($dbServer, $dbUser, $dbPass, $dbName);
		$access=2; //everyone
		if ($_SESSION['logged_in']==1){
			switch ($_SESSION['user_type']){
			   case 'registered':
			      $access+=4;
			      break;
			   case 'client':
			      $access+=4+8;
			      break;
			   case 'admin':
			      $access+=4+8+16;
			      break;
			   default:
			      $access=2;// this is actually an error.
			}	
		}

		$q="SELECT * FROM {$dbTableContent} WHERE (($num & category) AND ($access & access)) ORDER BY created DESC" ; 
		$result = mysql_query($q)
			or die(mysql_error());  
		$i=0;	
		$rows=array();
		while($row = mysql_fetch_array( $result )){	
			$rows[$i]=$row;
			$i++;}
	?>
	<script type="text/javascript">
	$(document).ready(function() {
		//Set default open/close settings
		$('.annotation').hide(); //Hide/close all containers
	//	$('.title:first').addClass('active').next().show(); //Add "active" class to first title, then show/open the immediate next container

		//On Click
		$('.title').click(function(){
			if( $(this).next().is(':hidden') ) { //If immediate next container is closed...
				$('.title').removeClass('active').next().slideUp(); //Remove all "active" state and slide up the immediate next container
				$(this).toggleClass('active').next().slideDown(); //Add "active" state to clicked trigger and slide down the immediate next container
			}
			else{
					$('.title').removeClass('active').next().slideUp();
			}
			return false; //Prevent the browser jump to the link anchor
		});

	});
	</script>
-->
<!--
		<body>
			<div id="container">
				<%= render '/layouts/header' %>
				<div id='middle'>
				<h1 id='dr'>Dr. <%= params[:doctor].capitalize %></h1>
    			<%	drs=["Quiet","Diet","Movement","Happiness"]
				nums=[2,4,8,16] %>
				<p id='consult'>Also consult: ";
				$i=0; $j=0;
				foreach ($drs as $dr){
					$num=$nums[$i];
					if ($dr!=$_REQUEST['dr']){
						echo "<a href='prescriptions.php?dr={$dr}&num={$num}'>Dr. {$dr}</a>";
						if($j!=2) echo ", "; //very ugly ...
						$j++;
					}
					$i++;
				}
				?>
				</p>
				-->
				<div class="clear"></div>


<!--
				<?php 	$i=0;
						foreach ($rows as $row) { $i++;
						?>
							<h2 class="title"><a href="#"><?php echo $row['title'];?></a></h2>
							<div class="annotation">
							<?php echo html_entity_decode($row['html_post']); ?>
							</div>
	<?php
			   				}
	?>
				<div class="clear"></div>
				<br /><br /><br />
				-->
				</div> <!-- middle -->
-->
	<body>
		<div id="container">
			<%= render 'layouts/header' %>
			<div id='middle'>
				<h1> This is a new header </h1>
			<%= render :text => params.inspect %>
			</div> <!-- middle -->
			<%= render 'layouts/footer' %>

			</div> <!-- container -->
		</body>
	</html>

app/views/doctors/main.html.erb
	<body>
		<div id="container">
		<%= render "/layouts/header" %>
			<div id="middle">
				<p> Four doctors. That many? How about a GP to take care of all the basics? After all, if all the basics are taken care of, who needs all the specialists? Well, this is the point; to obviate the presence of doctors in your life. Have them as friends, as tellers of interesting stories, as keepers of a peculiar understanding of the human condition.

				The four are really one: you! Exciting! Kind of frightening too. It means you have to ask yourself all sorts of questions, like "what are my needs regarding sleep-food-space-relationships-sex-work-vacation?" Or, "how did I feel after that workout?" The Four Doctors are there to help get some clue of what really makes us feel good, and what activities, foods, and lifestyle choices rob us of vitality. Ideally, this attention to meeting our needs and recognizing our wants provide an individual with motive, a foundation that maintains a center from which to grow healthier and happier.</p>
				<table > 

				<tr>
					<td class="drimage"><%= link_to (image_tag "drquiet.jpeg", :alt => "Dr. Quiet Image"), "/doctors/quiet"%></td>
					<td class="drimage"><%= link_to (image_tag "drdiet.jpeg", :alt => "Dr. Diet Image"), "/doctors/diet"%></td>
					<td class="drimage"><%= link_to (image_tag "drmovement.jpeg", :alt => "Dr. Movement Image"), "/doctors/movement"%></td>
					<td class="drimage"><%= link_to (image_tag "drhappiness.jpeg", :alt => "Dr. Happiness Image"), "/doctors/happiness"%>></td>
				</tr> 
				<tr>
					<td><h2><%= link_to "Dr Quiet", '/doctors/quiet'%></h2></a></td>
					<td><h2><%= link_to "Dr Diet", '/doctors/diet'%></h2></a></td>
					<td><h2><%= link_to "Dr Movement", '/doctors/movement'%></h2></a></td>
					<td><h2><%= link_to "Dr Happiness", '/doctors/happiness'%></h2></a></td>	
				</tr>

				<tr>
					<td><p>   Dr. Quiet is the physician in charge of energy management and recovery. When you’re overly stressed and your fight or flight system is triggered repeatedly or for long periods of time, one of the first things to suffer is your sleep. Unfortunately, your body’s ability to recover and repair itself is tied in very real, biological ways to the sleep that you get. Dr. Quiet’s primary duty is to encourage you to get the necessary sleep to recover from the challenges you faced the day before and to wake energized for the day to come. At the same time, Dr. Quiet guides you to get the relaxation and the self-time you need to stay calm, focused and energized during the day. For example, Dr. Quiet can show you how to get active rest during your workday that will help you to tackle your projects more efficiently and effectively than ever. In short, following Dr. Quiet’s specific guidelines and sleep recommendations will take you a long way towards permanent health and wellbeing.</p></td>
					<td>
						<p>Dr. Diet provides the foundation for wellbeing. Food and drink dramatically affect our energy levels and our biochemical reality, which in turn influences our emotional and our mental reality. In my 24 years of clinical practice as an International Holistic Health Practitioner, trainer and coach of athletes, I’ve seen over and over again that when the diet is deficient, there just isn’t enough energy or clarity of mind to initiate and sustain the changes needed for self-healing.</p>
						<p>As you’ll soon see, surprisingly, Dr. Diet won’t necessarily guide everyone to eat the same foods. In fact, the kinds of foods and the proportions of those foods that are right for you may vary quite radically from your friends and loved ones. Dr. Diet gives you the information you need to make the right nutritional choices for your body.</p></td>
					<td><p>Dr. Movement is my addition to our panel of inner Doctors. Over the course of history, humans have become more and more sedentary. We no longer have to hunt and gather just to feed ourselves. Our jobs and careers require us to sit most of the day in front of computer screens, and the daily demands of our life often keep us from any kind of beneficial physical movement. Daily movement isn’t simply necessary for keeping a trim figure or decreasing the risk of heart disease.  In fact, it’s necessary to get nutrients to and through our body, to move waste out of our bodies and to generate emotional stability and mental clarity. Dr. Movement is there to show you the way to acquire more life-force and how to move it into action so that you can truly experience and enjoy life.    
					</p></td>
					<td><p>Dr. Happiness is always there to lead us toward a life that fulfills our individual needs. Dr. Happiness advises us that if we lead a life that doesn’t fit with our core values and doesn’t fulfill us, every facet of our life becomes a burden. So, the less your current lifestyle fits with your core values, the more frequently you will be stressed and worn out. The important guiding truth that this Doctor offers is that happiness is an essential feature of genuine lasting health. Dr. Happiness shows you how to create and undertake the deep introspective study and intention to discover what makes you truly happy.</p></td>	
				</tr>

				</table>
			</div><!-- middle -->
		<%= render "/layouts/footer" %>


		</div><!-- container -->
	</body>

app/views/doctors/main.html.haml
<body>
	<div id="container">
	<%= render "/layouts/header" %>
		<div id="middle">
			<p> Four doctors. That many? How about a GP to take care of all the basics? After all, if all the basics are taken care of, who needs all the specialists? Well, this is the point; to obviate the presence of doctors in your life. Have them as friends, as tellers of interesting stories, as keepers of a peculiar understanding of the human condition.

			The four are really one: you! Exciting! Kind of frightening too. It means you have to ask yourself all sorts of questions, like "what are my needs regarding sleep-food-space-relationships-sex-work-vacation?" Or, "how did I feel after that workout?" The Four Doctors are there to help get some clue of what really makes us feel good, and what activities, foods, and lifestyle choices rob us of vitality. Ideally, this attention to meeting our needs and recognizing our wants provide an individual with motive, a foundation that maintains a center from which to grow healthier and happier.</p>
			<table > 

			<tr>
				<td class="drimage"><%= link_to (image_tag "drquiet.jpeg", :alt => "Dr. Quiet Image"), "/doctors/quiet"%></td>
				<td class="drimage"><%= link_to (image_tag "drdiet.jpeg", :alt => "Dr. Diet Image"), "/doctors/diet"%></td>
				<td class="drimage"><%= link_to (image_tag "drmovement.jpeg", :alt => "Dr. Movement Image"), "/doctors/movement"%></td>
				<td class="drimage"><%= link_to (image_tag "drhappiness.jpeg", :alt => "Dr. Happiness Image"), "/doctors/happiness"%>></td>
			</tr> 
			<tr>
				<td><h2><%= link_to "Dr Quiet", '/doctors/quiet'%></h2></a></td>
				<td><h2><%= link_to "Dr Diet", '/doctors/diet'%></h2></a></td>
				<td><h2><%= link_to "Dr Movement", '/doctors/movement'%></h2></a></td>
				<td><h2><%= link_to "Dr Happiness", '/doctors/happiness'%></h2></a></td>	
			</tr>

			<tr>
				<td><p>   Dr. Quiet is the physician in charge of energy management and recovery. When you’re overly stressed and your fight or flight system is triggered repeatedly or for long periods of time, one of the first things to suffer is your sleep. Unfortunately, your body’s ability to recover and repair itself is tied in very real, biological ways to the sleep that you get. Dr. Quiet’s primary duty is to encourage you to get the necessary sleep to recover from the challenges you faced the day before and to wake energized for the day to come. At the same time, Dr. Quiet guides you to get the relaxation and the self-time you need to stay calm, focused and energized during the day. For example, Dr. Quiet can show you how to get active rest during your workday that will help you to tackle your projects more efficiently and effectively than ever. In short, following Dr. Quiet’s specific guidelines and sleep recommendations will take you a long way towards permanent health and wellbeing.</p></td>
				<td>
					<p>Dr. Diet provides the foundation for wellbeing. Food and drink dramatically affect our energy levels and our biochemical reality, which in turn influences our emotional and our mental reality. In my 24 years of clinical practice as an International Holistic Health Practitioner, trainer and coach of athletes, I’ve seen over and over again that when the diet is deficient, there just isn’t enough energy or clarity of mind to initiate and sustain the changes needed for self-healing.</p>
					<p>As you’ll soon see, surprisingly, Dr. Diet won’t necessarily guide everyone to eat the same foods. In fact, the kinds of foods and the proportions of those foods that are right for you may vary quite radically from your friends and loved ones. Dr. Diet gives you the information you need to make the right nutritional choices for your body.</p></td>
				<td><p>Dr. Movement is my addition to our panel of inner Doctors. Over the course of history, humans have become more and more sedentary. We no longer have to hunt and gather just to feed ourselves. Our jobs and careers require us to sit most of the day in front of computer screens, and the daily demands of our life often keep us from any kind of beneficial physical movement. Daily movement isn’t simply necessary for keeping a trim figure or decreasing the risk of heart disease.  In fact, it’s necessary to get nutrients to and through our body, to move waste out of our bodies and to generate emotional stability and mental clarity. Dr. Movement is there to show you the way to acquire more life-force and how to move it into action so that you can truly experience and enjoy life.    
				</p></td>
				<td><p>Dr. Happiness is always there to lead us toward a life that fulfills our individual needs. Dr. Happiness advises us that if we lead a life that doesn’t fit with our core values and doesn’t fulfill us, every facet of our life becomes a burden. So, the less your current lifestyle fits with your core values, the more frequently you will be stressed and worn out. The important guiding truth that this Doctor offers is that happiness is an essential feature of genuine lasting health. Dr. Happiness shows you how to create and undertake the deep introspective study and intention to discover what makes you truly happy.</p></td>	
			</tr>

			</table>
		</div><!-- middle -->
	<%= render "/layouts/footer" %>


	</div><!-- container -->
</body>

app/views/layouts/_footer.html.erb
<div id="footer">
		<p>Copyright &copy; 2010-11 Travis E. Brown. All rights reserved.</p>
</div><!-- footer -->

app/views/layouts/_header.html.erb
<div id="header">
	<img id="logo" src="images/logo.png" alt="we need a logo"/>
	<div id="site-title" ><h1> Sage Body Health </h1></div>
<!-- <?php 
 	$message=sess_var('message');
	$_SESSION['message']=""; // let's not leave any pesky messages around - why doesn't this work.
	if( 1==sess_var('logged_in',0))
		echo	"<p id='welcome'> Hello {$_SESSION['first_name']}, <a href='logout.php'>Log out? </a></p>";
		else
	?> -->
	<p id='welcome'>Welcome Guest, <a href='login.php'>Login? </a></p>

	<br />
		<div class="clear"></div>
	<p id="message">No message here!!!</p>


	<div id="topnav">
		<ul>
			<li><a href="index.php">Home</a></li>
			<li><%= link_to 'Four Doctors', doctors_main_path %></li>
			<li><%= link_to 'Invitation to Health', doctors_main_path %></li>
			<li><%= link_to 'Personal Invites', doctors_main_path %></li>
			<li><%= link_to 'Useful Tools', doctors_main_path %></li>
			<li><%= link_to 'Contact Us',doctors_main_path %></li>
		</ul>
		<div class="clear"></div>
	</div><!-- topnav -->
</div> <!-- header -->
<div class="clear"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sagebody</title>
  <%= stylesheet_link_tag :all %>
  <%= stylesheet_link_tag "main" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
	<body>
		<div id="container">
 			<%= render "layouts/header" %>
			<div id='middle'>
				<h2> Sage Body Health </h2>
				<p>WELCOME! This site is an invitation to choose health. It starts with this premise: our chosen pace and complexity of life distracts us from the basic fact that we can only grow wise through reflection and experience. With our own well-being, it is no different. We are receiving information all the time, and it is up to us to pay attention. The best suggestion I can make to anyone seeking outstanding health is to listen carefully to the counsel of four doctors.
				Four doctors. That many? How about a GP to take care of all the basics? After all, if all the basics are taken care of, who needs all the specialists? Well, this is the point; to obviate the presence of doctors in your life. Have them as friends, as tellers of interesting stories, as keepers of a peculiar understanding of the human condition.
				</p>
				<p>The four are really one: you! Exciting! Kind of frightening too. It means you have to ask yourself all sorts of questions, like "what are my needs regarding sleep-food-space-relationships-sex-work-vacation?" Or, "how did I feel after that workout?" The Four Doctors are there to help get some clue of what really makes us feel good, and what activities, foods, and lifestyle choices rob us of vitality. Ideally, this attention to meeting our needs and recognizing our wants provide an individual with motive, a foundation that maintains a center from which to grow healthier and happier.
				</p>
				<p>Browse around the site. There is some material here to get anyone started on the road to better health. When you are ready to go further, and seek more tools to really feel GOOD, it will be my absolute pleasure to help you out.
				</p>
				<p>So, welcome again, and good health to you!</p>
				<br />
				<h2>Travis E. Brown </h2>
				<p><img  src="images/travis.png" alt="Travis" align="left"/>Travis grew up watching his older brothers play soccer and wrestle, and followed in their footsteps with a dual-sport career at NYU. Combining his academic studies with an already strong affinity for physical activity, Travis received his first personal training certification in 1996 and has been continually educating himself on the latest fitness findings and trends ever since. Travis enjoys bringing his knowledge and experience to the JCC clients and training staff, while always learning from his peers.
				</p>
				<p>	Certifications: CSCS, NASM, Pre/Post Natal, MES, BS Kinesiology</p>
				<br />
			</div>
			<div class="clear"></div>
			<%= render "layouts/footer" %>

		</div> <!-- container -->
	</body>
</html>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>